name: Fresh Collectibles
favicon: null
layout_spectrum: 0.973
typography_spectrum: 0.1008
title: Fresh Collectibles - the Personal Collection
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#040605'
    - '#f4030a'
    - '#5a5aa4'
    - '#d59e0e'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
